### ISSUE TITLE
Builds are not currently deterministic

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az-quickstart-scaffolding#5] opened 2020-01-31 16:03 UTC
**Describe the bug**
composer builds for this repo after a fresh clone are currently not deterministic because we do not commit our lock file and are using non-specific version constraints for our dependencies in composer.json

This leads to issues like the deprecated code check failure on @kevcooper's current [PR for az_quickstart](https://github.com/az-digital/az_quickstart/pull/16) which is happening due to a bug in a drupalcheck release that happened after we first added that dependency to this project.

**To Reproduce**
1. Clone this repository
2. Run composer install
4. (Possibly) see errors that didn't exist previously due to new dependency versions being released

**Expected behavior**
Deterministic builds

**Comment by barrettbaffert** [comment] 2020-01-31 17:26
This issue blocks `Update security email to az-digital-security@list.ariz…` #16
 among others

**Comment by joeparsons** [comment] 2020-01-31 17:37
drupalcheck bug causing the failure:
https://github.com/mglaman/drupal-check/issues/131

**Comment by trackleft** [comment] 2020-01-31 21:44
When running `composer update --prefer-lowest --prefer-dist --prefer-stable --no-interaction` I get
 ```                                                          
  [InvalidArgumentException]                              
  Package type "drupal-console-library" is not supported  
                                                          
```

**Comment by tadean** [comment] 2020-01-31 23:47
It looks like the `drupal-console-library` error is coming from an issue in `drupal/console-dotenv`, with `--prefer-lowest` it's loading quite an old version (`0.1.0`). `drupal-console-library` isn't currently a real package type handled by `composer/installers`. We could pin `drupal/console-dotenv` to a higher version or add an install location for that package type.

It looks like the library stopped referencing the `drupal-console-library` type in version `0.3.1` : https://github.com/weknowinc/drupal-console-dotenv/commit/367c5920a9411c3049793f2149fe337c93b4cb9b#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

Another alternative would be adding a line to the scaffolding's install location for that type of package:

        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/libraries/{$name}": ["type:drupal-library"],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "web/modules/custom/{$name}": ["type:drupal-custom-module"],
            "web/profiles/custom/{$name}": ["type:drupal-custom-profile"],
            "web/themes/custom/{$name}": ["type:drupal-custom-theme"],
            "drush/Commands/contrib/{$name}": ["type:drupal-drush"],
            "web/libraries/{$name}": ["type:drupal-console-library"]
        },

Given that it doesn't appear to be a support type of package any longer I think it'd lean in the direction of pinning the scaffolding to a higher version of the `drupal/console-dotenv` library.

**Comment by tadean** [comment] 2020-02-01 00:08
The addition of `"drupal/console-dotenv": "0.3.1",` to the `require` section seemed to clear up the `drupal-console-library` issue for me on `--prefer-lowest`.

**Comment by barrettbaffert** [comment] 2020-04-10 21:16
Closing as a duplicate of: https://github.com/az-digital/az-quickstart-scaffolding/issues/7 which closed when this was merged https://github.com/az-digital/az-quickstart-scaffolding/pull/8

**Closed by barrettbaffert** 2020-04-10 21:16 UTC
Labels: Blocker
